const INITIATOR_HELLO_LENGTH = 64
const RESPONDER_HELLO_LENGTH = 64
const INITIATOR_AUTHENTICATE_PLAINTEXT_LENGTH = 128
const INITIATOR_AUTHENTICATE_CIPHERTEXT_LENGTH = 144
const RESPONDER_AUTHENTICATE_PLAINTEXT_LENGTH = 64
const RESPONDER_AUTHENTICATE_CIPHERTEXT_LENGTH = 80

module.exports = {
  INITIATOR_HELLO_LENGTH,
  RESPONDER_HELLO_LENGTH,
  INITIATOR_AUTHENTICATE_PLAINTEXT_LENGTH,
  INITIATOR_AUTHENTICATE_CIPHERTEXT_LENGTH,
  RESPONDER_AUTHENTICATE_PLAINTEXT_LENGTH,
  RESPONDER_AUTHENTICATE_CIPHERTEXT_LENGTH,
}
